### ISSUE TITLE
Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by jeffery812** [windstormeye/SwiftGame#2]
你们都没有这个错吗？
![image](https://user-images.githubusercontent.com/5066926/64520805-29b51880-d2f7-11e9-9d50-ec7dd4b3d15f.png)

**Comment by jeffery812** [comment]
个人觉得， 代码中的这个强制解包习惯不好， 用的太多， 容易带坏小朋友。`if let` 是Swift的亮点， 应该用这个代替强制解包。

**Comment by windstormeye** [comment]
有，推荐使用 iPhone 7 模拟器打开，因为个人因素没法做到多设备尺寸的底图适配啦～现在在工程里的图是 iPhone 7 的尺寸设计的。

这些亮点都已经在代码中用上，不会走歪门邪道哒～这个地方是故意强制解包的。

感谢反馈！

**Comment by windstormeye** [comment]
有些地方强制解包是因为肯定不会传入 Optional 值，但之所以设计成 Optional 类型跟「黎锦拼图」这个游戏本身有些强关联，不过后续会在代码中留意该情况。

感谢反馈！
